dist: bionic
sudo: required
language: node_js
node_js: 12
stages:
  - build
  - publish
jobs:
  include:
    - stage: build
      name: build app
      before_script: npm i
      script: ng build --configuration production
      if: tag IS NOT present
    - stage: publish
      name: publish-app
      if: tag IS present
      before_script:
        - curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        - az config set extension.use_dynamic_install=yes_without_prompt
        - sh create-environment-prod-file.sh
        - npm i
      script: ./publish.sh
