dist: bionic
sudo: required
language: node_js
node_js: 12
stages:
  - build
  - publish
jobs:
  include:
    - stage: build
      name: build app
      before_script: npm i
      script: ng build --prod
      if: tag IS NOT present
    - stage: publish
      name: publish-app
      if: tag IS present
      services:
        - docker
      before_script:
        - docker login -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD} ${REGISTRY}
        - curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        - sh create-environment-prod-file.sh
        - npm i
      script: ./publish.sh
